# Generated by Django 5.0.2 on 2024-05-12 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
