# Generated by Django 5.0.2 on 2024-05-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certgen', '0002_alter_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificant_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_about',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_provider_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
