# Generated by Django 5.0.2 on 2024-05-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certgen', '0004_bulkcertificates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkcertificates',
            old_name='certificant_name',
            new_name='usernames',
        ),
    ]
